/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO., LTD
 * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
 *
 * See LICENSE file for details.
 */

#pragma once

#include "esp_gmf_method_helper.h"

#ifdef __cplusplus
extern "C" {
#endif  /* __cplusplus */

/**
 * @brief  Audio general method argument definition
 */
#define ESP_GMF_AUDIO_INDEX_ARG         "index"
#define ESP_GMF_AUDIO_GAIN_ARG          "gain"
#define ESP_GMF_AUDIO_BITS_ARG          "bits"
#define ESP_GMF_AUDIO_CHANNEL_ARG       "channel"
#define ESP_GMF_AUDIO_SAMPLE_RATE_ARG   "sample_rate"
#define ESP_GMF_AUDIO_BITRATE_ARG       "bitrate"
#define ESP_GMF_AUDIO_ENABLE_ARG        "enable"
#define ESP_GMF_AUDIO_TYPE_ARG          "type"
#define ESP_GMF_AUDIO_PARA_ARG          "para"
#define ESP_GMF_AUDIO_MODE_ARG          "mode"
#define ESP_GMF_AUDIO_SPEED_ARG         "speed"
#define ESP_GMF_AUDIO_PITCH_ARG         "pitch"
#define ESP_GMF_AUDIO_ROOM_SIZE_ARG     "room_size"
#define ESP_GMF_AUDIO_WET_LEVEL_ARG     "wet_level"
#define ESP_GMF_AUDIO_DELAY_TIME_ARG    "delay_time"
#define ESP_GMF_AUDIO_FEEDBACK_ARG      "feedback"
#define ESP_GMF_AUDIO_MIX_RATIO_ARG     "mix_ratio"
#define ESP_GMF_AUDIO_DAMPING_ARG       "damping"
#define ESP_GMF_AUDIO_DRY_LEVEL_ARG     "dry_level"
#define ESP_GMF_AUDIO_PRE_DELAY_ARG     "pre_delay_ms"
#define ESP_GMF_AUDIO_CURVE_ARG         "curve"
#define ESP_GMF_AUDIO_TRANSIT_TIME_ARG  "transit_time"
#define ESP_GMF_AUDIO_PAPR_TH_ARG       "papr_th"
#define ESP_GMF_AUDIO_PHPR_TH_ARG       "phpr_th"
#define ESP_GMF_AUDIO_PNPR_TH_ARG       "pnpr_th"
#define ESP_GMF_AUDIO_IMSD_TH_ARG       "imsd_th"
#define ESP_GMF_AUDIO_ENABLE_IMSD_ARG   "enable_imsd"
#define ESP_GMF_AUDIO_INSIZE_ARG        "in_size"
#define ESP_GMF_AUDIO_OUTSIZE_ARG       "out_size"
#define ESP_GMF_AUDIO_CFG_ARG           "cfg"
#define ESP_GMF_AUDIO_INFO_ARG          "info"

/**
 * @brief  Audio EQ parameter argument definition
 */
#define ESP_GMF_AUDIO_EQ_PARA_ARG       ESP_GMF_AUDIO_PARA_ARG
#define ESP_GMF_AUDIO_EQ_PARA_FT_ARG    ESP_GMF_AUDIO_TYPE_ARG
#define ESP_GMF_AUDIO_EQ_PARA_GAIN_ARG  ESP_GMF_AUDIO_GAIN_ARG
#define ESP_GMF_AUDIO_EQ_PARA_FC_ARG    "fc"
#define ESP_GMF_AUDIO_EQ_PARA_Q_ARG     "q"

/**
 * @brief  Audio DRC parameter argument definition
 */
#define ESP_GMF_AUDIO_DRC_MAKEUP_ARG     ESP_GMF_AUDIO_GAIN_ARG
#define ESP_GMF_AUDIO_DRC_ATTACK_ARG     "attack"
#define ESP_GMF_AUDIO_DRC_RELEASE_ARG    "release"
#define ESP_GMF_AUDIO_DRC_HOLD_ARG       "hold"
#define ESP_GMF_AUDIO_DRC_KNEE_ARG       "knee"
#define ESP_GMF_AUDIO_DRC_POINTS_ARG     "points"
#define ESP_GMF_AUDIO_DRC_POINT_NUM_ARG  "point_num"
#define ESP_GMF_AUDIO_DRC_POINT_X_ARG    "x"
#define ESP_GMF_AUDIO_DRC_POINT_Y_ARG    "y"

/**
 * @brief  Audio MBC parameter argument definition
 */
#define ESP_GMF_AUDIO_MBC_FC_ARG              "fc"
#define ESP_GMF_AUDIO_MBC_PARA_ARG            ESP_GMF_AUDIO_PARA_ARG
#define ESP_GMF_AUDIO_MBC_PARA_MAKEUP_ARG     ESP_GMF_AUDIO_GAIN_ARG
#define ESP_GMF_AUDIO_MBC_PARA_THRESHOLD_ARG  "threshold"
#define ESP_GMF_AUDIO_MBC_PARA_RATIO_ARG      "ratio"
#define ESP_GMF_AUDIO_MBC_PARA_ATTACK_ARG     "attack"
#define ESP_GMF_AUDIO_MBC_PARA_RELEASE_ARG    "release"
#define ESP_GMF_AUDIO_MBC_PARA_HOLD_ARG       "hold"
#define ESP_GMF_AUDIO_MBC_PARA_KNEE_ARG       "knee"

/**
 * @brief  Audio general config parameter argument definition
 */
#define ESP_GMF_AUDIO_CFG_TYPE_ARG       ESP_GMF_AUDIO_TYPE_ARG
#define ESP_GMF_AUDIO_CFG_SUBCFGPTR_ARG  "sub_cfg"
#define ESP_GMF_AUDIO_CFG_SUBCFGSZ_ARG   "sub_cfg_sz"

/**
 * @brief  Audio sound information parameter argument definition
 */
#define ESP_GMF_AUDIO_SND_INFO_ARG             ESP_GMF_AUDIO_INFO_ARG
#define ESP_GMF_AUDIO_SND_INFO_TYPE_ARG        ESP_GMF_AUDIO_TYPE_ARG
#define ESP_GMF_AUDIO_SND_INFO_SAMPLERATE_ARG  ESP_GMF_AUDIO_SAMPLE_RATE_ARG
#define ESP_GMF_AUDIO_SND_INFO_BITRATE_ARG     ESP_GMF_AUDIO_BITRATE_ARG
#define ESP_GMF_AUDIO_SND_INFO_CHANNEL_ARG     ESP_GMF_AUDIO_CHANNEL_ARG
#define ESP_GMF_AUDIO_SND_INFO_BITS_ARG        ESP_GMF_AUDIO_BITS_ARG

/**
 * @brief  GMF audio method definition
 */
#define AMETHOD_DEF(module, method, str)  ESP_GMF_METHOD_DEF(AUDIO, module, method, str)

/**
 * @brief  Get GMF audio method string
 */
#define AMETHOD(module, method)  ESP_GMF_METHOD_STR(AUDIO, module, method)

/**
 * @brief  GMF audio method argument definition
 */
#define AMETHOD_ARG_DEF(module, method, arg, str)  ESP_GMF_METHOD_ARG_DEF(AUDIO, module, method, arg, str)

/**
 * @brief  Get GMF audio method argument string
 */
#define AMETHOD_ARG(module, method, arg)  ESP_GMF_METHOD_ARG_STR(AUDIO, module, method, arg)

/**
 * @brief  ALC method
 */
AMETHOD_DEF(ALC, SET_GAIN, "set_gain");
AMETHOD_ARG_DEF(ALC, SET_GAIN, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(ALC, SET_GAIN, GAIN, ESP_GMF_AUDIO_GAIN_ARG);

AMETHOD_DEF(ALC, GET_GAIN, "get_gain");
AMETHOD_ARG_DEF(ALC, GET_GAIN, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(ALC, GET_GAIN, GAIN, ESP_GMF_AUDIO_GAIN_ARG);

AMETHOD_DEF(ALC, SET_TRANSIT_TIME, "set_transit_time");
AMETHOD_ARG_DEF(ALC, SET_TRANSIT_TIME, TRANSIT_TIME, ESP_GMF_AUDIO_TRANSIT_TIME_ARG);

AMETHOD_DEF(ALC, GET_TRANSIT_TIME, "get_transit_time");
AMETHOD_ARG_DEF(ALC, GET_TRANSIT_TIME, TRANSIT_TIME, ESP_GMF_AUDIO_TRANSIT_TIME_ARG);

/**
 * @brief  BIT CVT method
 */
AMETHOD_DEF(BIT_CVT, SET_DEST_BITS, "set_dest_bits");
AMETHOD_ARG_DEF(BIT_CVT, SET_DEST_BITS, BITS, ESP_GMF_AUDIO_BITS_ARG);

AMETHOD_DEF(BIT_CVT, GET_DEST_BITS, "get_dest_bits");
AMETHOD_ARG_DEF(BIT_CVT, GET_DEST_BITS, BITS, ESP_GMF_AUDIO_BITS_ARG);

/**
 * @brief  CH CVT method
 */
AMETHOD_DEF(CH_CVT, SET_DEST_CH, "set_dest_ch");
AMETHOD_ARG_DEF(CH_CVT, SET_DEST_CH, CH, ESP_GMF_AUDIO_CHANNEL_ARG);

AMETHOD_DEF(CH_CVT, GET_DEST_CH, "get_dest_ch");
AMETHOD_ARG_DEF(CH_CVT, GET_DEST_CH, CH, ESP_GMF_AUDIO_CHANNEL_ARG);

/**
 * @brief  RATE CVT method
 */
AMETHOD_DEF(RATE_CVT, SET_DEST_RATE, "set_dest_rate");
AMETHOD_ARG_DEF(RATE_CVT, SET_DEST_RATE, RATE, ESP_GMF_AUDIO_SAMPLE_RATE_ARG);

AMETHOD_DEF(RATE_CVT, GET_DEST_RATE, "get_dest_rate");
AMETHOD_ARG_DEF(RATE_CVT, GET_DEST_RATE, RATE, ESP_GMF_AUDIO_SAMPLE_RATE_ARG);

/**
 * @brief  EQ method
 */
AMETHOD_DEF(EQ, SET_PARA, "set_para");
AMETHOD_ARG_DEF(EQ, SET_PARA, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(EQ, SET_PARA, PARA, ESP_GMF_AUDIO_EQ_PARA_ARG);
AMETHOD_ARG_DEF(EQ, SET_PARA, PARA_FT, ESP_GMF_AUDIO_EQ_PARA_FT_ARG);
AMETHOD_ARG_DEF(EQ, SET_PARA, PARA_FC, ESP_GMF_AUDIO_EQ_PARA_FC_ARG);
AMETHOD_ARG_DEF(EQ, SET_PARA, PARA_Q, ESP_GMF_AUDIO_EQ_PARA_Q_ARG);
AMETHOD_ARG_DEF(EQ, SET_PARA, PARA_GAIN, ESP_GMF_AUDIO_EQ_PARA_GAIN_ARG);

AMETHOD_DEF(EQ, GET_PARA, "get_para");
AMETHOD_ARG_DEF(EQ, GET_PARA, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(EQ, GET_PARA, PARA, ESP_GMF_AUDIO_EQ_PARA_ARG);
AMETHOD_ARG_DEF(EQ, GET_PARA, PARA_FT, ESP_GMF_AUDIO_EQ_PARA_FT_ARG);
AMETHOD_ARG_DEF(EQ, GET_PARA, PARA_FC, ESP_GMF_AUDIO_EQ_PARA_FC_ARG);
AMETHOD_ARG_DEF(EQ, GET_PARA, PARA_Q, ESP_GMF_AUDIO_EQ_PARA_Q_ARG);
AMETHOD_ARG_DEF(EQ, GET_PARA, PARA_GAIN, ESP_GMF_AUDIO_EQ_PARA_GAIN_ARG);

AMETHOD_DEF(EQ, ENABLE_FILTER, "enable_filter");
AMETHOD_ARG_DEF(EQ, ENABLE_FILTER, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(EQ, ENABLE_FILTER, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

AMETHOD_DEF(EQ, GET_ENABLE_FILTER, "get_enable_filter");
AMETHOD_ARG_DEF(EQ, GET_ENABLE_FILTER, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(EQ, GET_ENABLE_FILTER, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

AMETHOD_DEF(EQ, SET_FILTER_NUM, "set_filter_num");
AMETHOD_ARG_DEF(EQ, SET_FILTER_NUM, FILTER_NUM, "filter_num");

AMETHOD_DEF(EQ, GET_FILTER_NUM, "get_filter_num");
AMETHOD_ARG_DEF(EQ, GET_FILTER_NUM, FILTER_NUM, "filter_num");

/**
 * @brief  DRC method
 */
AMETHOD_DEF(DRC, SET_ATTACK, "set_attack");
AMETHOD_ARG_DEF(DRC, SET_ATTACK, ATTACK, ESP_GMF_AUDIO_DRC_ATTACK_ARG);

AMETHOD_DEF(DRC, GET_ATTACK, "get_attack");
AMETHOD_ARG_DEF(DRC, GET_ATTACK, ATTACK, ESP_GMF_AUDIO_DRC_ATTACK_ARG);

AMETHOD_DEF(DRC, SET_RELEASE, "set_release");
AMETHOD_ARG_DEF(DRC, SET_RELEASE, RELEASE, ESP_GMF_AUDIO_DRC_RELEASE_ARG);

AMETHOD_DEF(DRC, GET_RELEASE, "get_release");
AMETHOD_ARG_DEF(DRC, GET_RELEASE, RELEASE, ESP_GMF_AUDIO_DRC_RELEASE_ARG);

AMETHOD_DEF(DRC, SET_HOLD, "set_hold");
AMETHOD_ARG_DEF(DRC, SET_HOLD, HOLD, ESP_GMF_AUDIO_DRC_HOLD_ARG);

AMETHOD_DEF(DRC, GET_HOLD, "get_hold");
AMETHOD_ARG_DEF(DRC, GET_HOLD, HOLD, ESP_GMF_AUDIO_DRC_HOLD_ARG);

AMETHOD_DEF(DRC, SET_MAKEUP, "set_makeup");
AMETHOD_ARG_DEF(DRC, SET_MAKEUP, MAKEUP, ESP_GMF_AUDIO_DRC_MAKEUP_ARG);

AMETHOD_DEF(DRC, GET_MAKEUP, "get_makeup");
AMETHOD_ARG_DEF(DRC, GET_MAKEUP, MAKEUP, ESP_GMF_AUDIO_DRC_MAKEUP_ARG);

AMETHOD_DEF(DRC, SET_KNEE, "set_knee");
AMETHOD_ARG_DEF(DRC, SET_KNEE, KNEE, ESP_GMF_AUDIO_DRC_KNEE_ARG);

AMETHOD_DEF(DRC, GET_KNEE, "get_knee");
AMETHOD_ARG_DEF(DRC, GET_KNEE, KNEE, ESP_GMF_AUDIO_DRC_KNEE_ARG);

AMETHOD_DEF(DRC, SET_POINTS, "set_points");
AMETHOD_ARG_DEF(DRC, SET_POINTS, POINTS, ESP_GMF_AUDIO_DRC_POINTS_ARG);
AMETHOD_ARG_DEF(DRC, SET_POINTS, POINT_NUM, ESP_GMF_AUDIO_DRC_POINT_NUM_ARG);

AMETHOD_DEF(DRC, GET_POINT_NUM, "get_point_num");
AMETHOD_ARG_DEF(DRC, GET_POINT_NUM, POINT_NUM, ESP_GMF_AUDIO_DRC_POINT_NUM_ARG);

AMETHOD_DEF(DRC, GET_POINTS, "get_points");
AMETHOD_ARG_DEF(DRC, GET_POINTS, POINTS, ESP_GMF_AUDIO_DRC_POINTS_ARG);
AMETHOD_ARG_DEF(DRC, GET_POINTS, POINT_NUM, ESP_GMF_AUDIO_DRC_POINT_NUM_ARG);

AMETHOD_DEF(DRC, SET_POINT, "set_point");
AMETHOD_ARG_DEF(DRC, SET_POINT, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(DRC, SET_POINT, X, ESP_GMF_AUDIO_DRC_POINT_X_ARG);
AMETHOD_ARG_DEF(DRC, SET_POINT, Y, ESP_GMF_AUDIO_DRC_POINT_Y_ARG);

AMETHOD_DEF(DRC, GET_POINT, "get_point");
AMETHOD_ARG_DEF(DRC, GET_POINT, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(DRC, GET_POINT, X, ESP_GMF_AUDIO_DRC_POINT_X_ARG);
AMETHOD_ARG_DEF(DRC, GET_POINT, Y, ESP_GMF_AUDIO_DRC_POINT_Y_ARG);

AMETHOD_DEF(DRC, SET_POINT_NUM, "set_point_num");
AMETHOD_ARG_DEF(DRC, SET_POINT_NUM, POINT_NUM, ESP_GMF_AUDIO_DRC_POINT_NUM_ARG);

/**
 * @brief  MBC method
 */
AMETHOD_DEF(MBC, SET_PARA, "set_para");
AMETHOD_ARG_DEF(MBC, SET_PARA, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA, ESP_GMF_AUDIO_MBC_PARA_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_THRESHOLD, ESP_GMF_AUDIO_MBC_PARA_THRESHOLD_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_RATIO, ESP_GMF_AUDIO_MBC_PARA_RATIO_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_MAKEUP, ESP_GMF_AUDIO_MBC_PARA_MAKEUP_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_ATTACK, ESP_GMF_AUDIO_MBC_PARA_ATTACK_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_RELEASE, ESP_GMF_AUDIO_MBC_PARA_RELEASE_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_HOLD, ESP_GMF_AUDIO_MBC_PARA_HOLD_ARG);
AMETHOD_ARG_DEF(MBC, SET_PARA, PARA_KNEE, ESP_GMF_AUDIO_MBC_PARA_KNEE_ARG);

AMETHOD_DEF(MBC, GET_PARA, "get_para");
AMETHOD_ARG_DEF(MBC, GET_PARA, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA, ESP_GMF_AUDIO_MBC_PARA_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_THRESHOLD, ESP_GMF_AUDIO_MBC_PARA_THRESHOLD_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_RATIO, ESP_GMF_AUDIO_MBC_PARA_RATIO_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_MAKEUP, ESP_GMF_AUDIO_MBC_PARA_MAKEUP_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_ATTACK, ESP_GMF_AUDIO_MBC_PARA_ATTACK_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_RELEASE, ESP_GMF_AUDIO_MBC_PARA_RELEASE_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_HOLD, ESP_GMF_AUDIO_MBC_PARA_HOLD_ARG);
AMETHOD_ARG_DEF(MBC, GET_PARA, PARA_KNEE, ESP_GMF_AUDIO_MBC_PARA_KNEE_ARG);

AMETHOD_DEF(MBC, SET_FC, "set_fc");
AMETHOD_ARG_DEF(MBC, SET_FC, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, SET_FC, FC, ESP_GMF_AUDIO_MBC_FC_ARG);

AMETHOD_DEF(MBC, GET_FC, "get_fc");
AMETHOD_ARG_DEF(MBC, GET_FC, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, GET_FC, FC, ESP_GMF_AUDIO_MBC_FC_ARG);

AMETHOD_DEF(MBC, SET_SOLO, "set_solo");
AMETHOD_ARG_DEF(MBC, SET_SOLO, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, SET_SOLO, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

AMETHOD_DEF(MBC, GET_SOLO, "get_solo");
AMETHOD_ARG_DEF(MBC, GET_SOLO, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, GET_SOLO, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

AMETHOD_DEF(MBC, SET_BYPASS, "set_bypass");
AMETHOD_ARG_DEF(MBC, SET_BYPASS, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, SET_BYPASS, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

AMETHOD_DEF(MBC, GET_BYPASS, "get_bypass");
AMETHOD_ARG_DEF(MBC, GET_BYPASS, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MBC, GET_BYPASS, ENABLE, ESP_GMF_AUDIO_ENABLE_ARG);

/**
 * @brief  FADE method
 */
AMETHOD_DEF(FADE, SET_MODE, "set_mode");
AMETHOD_ARG_DEF(FADE, SET_MODE, MODE, ESP_GMF_AUDIO_MODE_ARG);

AMETHOD_DEF(FADE, GET_MODE, "get_mode");
AMETHOD_ARG_DEF(FADE, GET_MODE, MODE, ESP_GMF_AUDIO_MODE_ARG);

AMETHOD_DEF(FADE, SET_CURVE, "set_curve");
AMETHOD_ARG_DEF(FADE, SET_CURVE, CURVE, ESP_GMF_AUDIO_CURVE_ARG);

AMETHOD_DEF(FADE, GET_CURVE, "get_curve");
AMETHOD_ARG_DEF(FADE, GET_CURVE, CURVE, ESP_GMF_AUDIO_CURVE_ARG);

AMETHOD_DEF(FADE, SET_TRANSIT_TIME, "set_transit_time");
AMETHOD_ARG_DEF(FADE, SET_TRANSIT_TIME, TRANSIT_TIME, ESP_GMF_AUDIO_TRANSIT_TIME_ARG);

AMETHOD_DEF(FADE, GET_TRANSIT_TIME, "get_transit_time");
AMETHOD_ARG_DEF(FADE, GET_TRANSIT_TIME, TRANSIT_TIME, ESP_GMF_AUDIO_TRANSIT_TIME_ARG);

AMETHOD_DEF(FADE, RESET, "reset");

/**
 * @brief  REVERB method
 */
AMETHOD_DEF(REVERB, SET_ROOM_SIZE, "set_room_size");
AMETHOD_ARG_DEF(REVERB, SET_ROOM_SIZE, ROOM_SIZE, ESP_GMF_AUDIO_ROOM_SIZE_ARG);

AMETHOD_DEF(REVERB, GET_ROOM_SIZE, "get_room_size");
AMETHOD_ARG_DEF(REVERB, GET_ROOM_SIZE, ROOM_SIZE, ESP_GMF_AUDIO_ROOM_SIZE_ARG);

AMETHOD_DEF(REVERB, SET_WET_LEVEL, "set_wet_level");
AMETHOD_ARG_DEF(REVERB, SET_WET_LEVEL, WET_LEVEL, ESP_GMF_AUDIO_WET_LEVEL_ARG);

AMETHOD_DEF(REVERB, GET_WET_LEVEL, "get_wet_level");
AMETHOD_ARG_DEF(REVERB, GET_WET_LEVEL, WET_LEVEL, ESP_GMF_AUDIO_WET_LEVEL_ARG);

AMETHOD_DEF(REVERB, SET_DAMPING, "set_damping");
AMETHOD_ARG_DEF(REVERB, SET_DAMPING, DAMPING, ESP_GMF_AUDIO_DAMPING_ARG);

AMETHOD_DEF(REVERB, GET_DAMPING, "get_damping");
AMETHOD_ARG_DEF(REVERB, GET_DAMPING, DAMPING, ESP_GMF_AUDIO_DAMPING_ARG);

AMETHOD_DEF(REVERB, SET_DRY_LEVEL, "set_dry_level");
AMETHOD_ARG_DEF(REVERB, SET_DRY_LEVEL, DRY_LEVEL, ESP_GMF_AUDIO_DRY_LEVEL_ARG);

AMETHOD_DEF(REVERB, GET_DRY_LEVEL, "get_dry_level");
AMETHOD_ARG_DEF(REVERB, GET_DRY_LEVEL, DRY_LEVEL, ESP_GMF_AUDIO_DRY_LEVEL_ARG);

AMETHOD_DEF(REVERB, SET_PRE_DELAY, "set_pre_delay_ms");
AMETHOD_ARG_DEF(REVERB, SET_PRE_DELAY, PRE_DELAY, ESP_GMF_AUDIO_PRE_DELAY_ARG);

AMETHOD_DEF(REVERB, GET_PRE_DELAY, "get_pre_delay_ms");
AMETHOD_ARG_DEF(REVERB, GET_PRE_DELAY, PRE_DELAY, ESP_GMF_AUDIO_PRE_DELAY_ARG);

AMETHOD_DEF(REVERB, RESET, "reset");

/**
 * @brief  HOWL method
 */
AMETHOD_DEF(HOWL, SET_PAPR_TH, "set_papr_th");
AMETHOD_ARG_DEF(HOWL, SET_PAPR_TH, PAPR_TH, ESP_GMF_AUDIO_PAPR_TH_ARG);

AMETHOD_DEF(HOWL, GET_PAPR_TH, "get_papr_th");
AMETHOD_ARG_DEF(HOWL, GET_PAPR_TH, PAPR_TH, ESP_GMF_AUDIO_PAPR_TH_ARG);

AMETHOD_DEF(HOWL, SET_PHPR_TH, "set_phpr_th");
AMETHOD_ARG_DEF(HOWL, SET_PHPR_TH, PHPR_TH, ESP_GMF_AUDIO_PHPR_TH_ARG);

AMETHOD_DEF(HOWL, GET_PHPR_TH, "get_phpr_th");
AMETHOD_ARG_DEF(HOWL, GET_PHPR_TH, PHPR_TH, ESP_GMF_AUDIO_PHPR_TH_ARG);

AMETHOD_DEF(HOWL, SET_PNPR_TH, "set_pnpr_th");
AMETHOD_ARG_DEF(HOWL, SET_PNPR_TH, PNPR_TH, ESP_GMF_AUDIO_PNPR_TH_ARG);

AMETHOD_DEF(HOWL, GET_PNPR_TH, "get_pnpr_th");
AMETHOD_ARG_DEF(HOWL, GET_PNPR_TH, PNPR_TH, ESP_GMF_AUDIO_PNPR_TH_ARG);

AMETHOD_DEF(HOWL, SET_IMSD_TH, "set_imsd_th");
AMETHOD_ARG_DEF(HOWL, SET_IMSD_TH, IMSD_TH, ESP_GMF_AUDIO_IMSD_TH_ARG);

AMETHOD_DEF(HOWL, GET_IMSD_TH, "get_imsd_th");
AMETHOD_ARG_DEF(HOWL, GET_IMSD_TH, IMSD_TH, ESP_GMF_AUDIO_IMSD_TH_ARG);

AMETHOD_DEF(HOWL, SET_ENABLE_IMSD, "enable_imsd");
AMETHOD_ARG_DEF(HOWL, SET_ENABLE_IMSD, ENABLE_IMSD, ESP_GMF_AUDIO_ENABLE_IMSD_ARG);

AMETHOD_DEF(HOWL, GET_ENABLE_IMSD, "is_imsd_enabled");
AMETHOD_ARG_DEF(HOWL, GET_ENABLE_IMSD, ENABLE_IMSD, ESP_GMF_AUDIO_ENABLE_IMSD_ARG);

/**
 * @brief  DELAY method
 */
AMETHOD_DEF(DELAY, SET_DELAY_TIME, "set_delay_time");
AMETHOD_ARG_DEF(DELAY, SET_DELAY_TIME, DELAY_TIME, ESP_GMF_AUDIO_DELAY_TIME_ARG);

AMETHOD_DEF(DELAY, GET_DELAY_TIME, "get_delay_time");
AMETHOD_ARG_DEF(DELAY, GET_DELAY_TIME, DELAY_TIME, ESP_GMF_AUDIO_DELAY_TIME_ARG);

AMETHOD_DEF(DELAY, SET_FEEDBACK, "set_feedback");
AMETHOD_ARG_DEF(DELAY, SET_FEEDBACK, FEEDBACK, ESP_GMF_AUDIO_FEEDBACK_ARG);

AMETHOD_DEF(DELAY, GET_FEEDBACK, "get_feedback");
AMETHOD_ARG_DEF(DELAY, GET_FEEDBACK, FEEDBACK, ESP_GMF_AUDIO_FEEDBACK_ARG);

AMETHOD_DEF(DELAY, SET_MIX_RATIO, "set_mix_ratio");
AMETHOD_ARG_DEF(DELAY, SET_MIX_RATIO, MIX_RATIO, ESP_GMF_AUDIO_MIX_RATIO_ARG);

AMETHOD_DEF(DELAY, GET_MIX_RATIO, "get_mix_ratio");
AMETHOD_ARG_DEF(DELAY, GET_MIX_RATIO, MIX_RATIO, ESP_GMF_AUDIO_MIX_RATIO_ARG);

AMETHOD_DEF(DELAY, RESET, "reset");

/**
 * @brief  MIXER method
 */
AMETHOD_DEF(MIXER, SET_MODE, "set_mode");
AMETHOD_ARG_DEF(MIXER, SET_MODE, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MIXER, SET_MODE, MODE, ESP_GMF_AUDIO_MODE_ARG);

AMETHOD_DEF(MIXER, GET_MODE, "get_mode");
AMETHOD_ARG_DEF(MIXER, GET_MODE, IDX, ESP_GMF_AUDIO_INDEX_ARG);
AMETHOD_ARG_DEF(MIXER, GET_MODE, MODE, ESP_GMF_AUDIO_MODE_ARG);

AMETHOD_DEF(MIXER, SET_INFO, "set_info");
AMETHOD_ARG_DEF(MIXER, SET_INFO, RATE, ESP_GMF_AUDIO_SAMPLE_RATE_ARG);
AMETHOD_ARG_DEF(MIXER, SET_INFO, CH, ESP_GMF_AUDIO_CHANNEL_ARG);
AMETHOD_ARG_DEF(MIXER, SET_INFO, BITS, ESP_GMF_AUDIO_BITS_ARG);

AMETHOD_DEF(MIXER, GET_INFO, "get_info");
AMETHOD_ARG_DEF(MIXER, GET_INFO, RATE, ESP_GMF_AUDIO_SAMPLE_RATE_ARG);
AMETHOD_ARG_DEF(MIXER, GET_INFO, CH, ESP_GMF_AUDIO_CHANNEL_ARG);
AMETHOD_ARG_DEF(MIXER, GET_INFO, BITS, ESP_GMF_AUDIO_BITS_ARG);

/**
 * @brief  SONIC method
 */
AMETHOD_DEF(SONIC, SET_SPEED, "set_speed");
AMETHOD_ARG_DEF(SONIC, SET_SPEED, SPEED, ESP_GMF_AUDIO_SPEED_ARG);

AMETHOD_DEF(SONIC, GET_SPEED, "get_speed");
AMETHOD_ARG_DEF(SONIC, GET_SPEED, SPEED, ESP_GMF_AUDIO_SPEED_ARG);

AMETHOD_DEF(SONIC, SET_PITCH, "set_pitch");
AMETHOD_ARG_DEF(SONIC, SET_PITCH, PITCH, ESP_GMF_AUDIO_PITCH_ARG);

AMETHOD_DEF(SONIC, GET_PITCH, "get_pitch");
AMETHOD_ARG_DEF(SONIC, GET_PITCH, PITCH, ESP_GMF_AUDIO_PITCH_ARG);

/**
 * @brief  ENCODER method
 */
AMETHOD_DEF(ENCODER, GET_FRAME_SZ, "get_frame_sz");
AMETHOD_ARG_DEF(ENCODER, GET_FRAME_SZ, INSIZE, ESP_GMF_AUDIO_INSIZE_ARG);
AMETHOD_ARG_DEF(ENCODER, GET_FRAME_SZ, OUTSIZE, ESP_GMF_AUDIO_OUTSIZE_ARG);

AMETHOD_DEF(ENCODER, SET_BITRATE, "set_bitrate");
AMETHOD_ARG_DEF(ENCODER, SET_BITRATE, BITRATE, ESP_GMF_AUDIO_BITRATE_ARG);

AMETHOD_DEF(ENCODER, GET_BITRATE, "get_bitrate");
AMETHOD_ARG_DEF(ENCODER, GET_BITRATE, BITRATE, ESP_GMF_AUDIO_BITRATE_ARG);

AMETHOD_DEF(ENCODER, RECONFIG, "recfg");
AMETHOD_ARG_DEF(ENCODER, RECONFIG, CFG, ESP_GMF_AUDIO_CFG_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG, CFG_TYPE, ESP_GMF_AUDIO_CFG_TYPE_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG, CFG_SUBCFGPTR, ESP_GMF_AUDIO_CFG_SUBCFGPTR_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG, CFG_SUBCFGSZ, ESP_GMF_AUDIO_CFG_SUBCFGSZ_ARG);

AMETHOD_DEF(ENCODER, RECONFIG_BY_SND_INFO, "recfg_by_sndinfo");
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO, ESP_GMF_AUDIO_SND_INFO_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO_TYPE, ESP_GMF_AUDIO_SND_INFO_TYPE_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO_SAMPLERATE, ESP_GMF_AUDIO_SND_INFO_SAMPLERATE_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO_BITRATE, ESP_GMF_AUDIO_SND_INFO_BITRATE_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO_CHANNEL, ESP_GMF_AUDIO_SND_INFO_CHANNEL_ARG);
AMETHOD_ARG_DEF(ENCODER, RECONFIG_BY_SND_INFO, INFO_BITS, ESP_GMF_AUDIO_SND_INFO_BITS_ARG);

/**
 * @brief  DECODER method
 */
AMETHOD_DEF(DECODER, RECONFIG, "recfg");
AMETHOD_ARG_DEF(DECODER, RECONFIG, CFG, ESP_GMF_AUDIO_CFG_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG, CFG_TYPE, ESP_GMF_AUDIO_CFG_TYPE_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG, CFG_SUBCFGPTR, ESP_GMF_AUDIO_CFG_SUBCFGPTR_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG, CFG_SUBCFGSZ, ESP_GMF_AUDIO_CFG_SUBCFGSZ_ARG);

AMETHOD_DEF(DECODER, RECONFIG_BY_SND_INFO, "recfg_by_sndinfo");
AMETHOD_ARG_DEF(DECODER, RECONFIG_BY_SND_INFO, INFO, ESP_GMF_AUDIO_SND_INFO_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG_BY_SND_INFO, INFO_TYPE, ESP_GMF_AUDIO_SND_INFO_TYPE_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG_BY_SND_INFO, INFO_SAMPLERATE, ESP_GMF_AUDIO_SND_INFO_SAMPLERATE_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG_BY_SND_INFO, INFO_CHANNEL, ESP_GMF_AUDIO_SND_INFO_CHANNEL_ARG);
AMETHOD_ARG_DEF(DECODER, RECONFIG_BY_SND_INFO, INFO_BITS, ESP_GMF_AUDIO_SND_INFO_BITS_ARG);

#ifdef __cplusplus
}
#endif  /* __cplusplus */
