name: Push components to https://components.espressif.com
on:
  push:
    branches:
      - main
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload components to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            gmf_core:./gmf_core
            gmf_audio:./gmf_elements/gmf_audio
            gmf_io:./gmf_elements/gmf_io
            gmf_misc:./gmf_elements/gmf_misc
            esp_audio_simple_player:./examples/esp_audio_simple_player
            gmf_ai_audio:./gmf_elements/gmf_ai_audio
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
