# The file mainly marks apps with special rules, while other apps are enabled by default

.disable_test_apps: &disable_test_apps
  disable:
    - if: TARGET_DIR_TYPE == "test_apps"

.disable_example: &disable_example
  disable:
    - if: TARGET_DIR_TYPE == "example"

gmf_core/test_apps:
  <<: *disable_example
