# The file mainly marks apps with special rules, while other apps are enabled by default

.disable_test_apps: &disable_test_apps
  disable:
    - if: TARGET_DIR_TYPE == "test_apps"

.disable_example: &disable_example
  disable:
    - if: TARGET_DIR_TYPE == "example"

.disable_test_apps_esp32: &disable_test_apps_esp32
  disable:
    - if: TARGET_DIR_TYPE == "test_apps" AND IDF_TARGET == "esp32"

gmf_core/test_apps:
  <<: *disable_example

packages/esp_board_manager:
  <<: *disable_test_apps_esp32